baseURL = "https://mars-tilu.github.io/blog-source/"
languageCode = "zh-cn"
title = "我的个人博客"
theme = "PaperMod"

[
params
]
author = "mars-tilu"
defaultTheme = "auto"
ShowCodeCopyButtons = true
ShowPostNavLinks = true

[
menu
]
[[
menu.main
]]
name = "首页"
url = "/"
weight = 1
[[
menu.main
]]
name = "文章"
url = "/posts/"
weight = 2

[
paginate
]
pageSize = 8